#!/bin/bash
# Weekly Tier 2 source scan — runs via system cron Monday 6 AM IST
# Uses Accenture Claude subscription via headless `claude --print` invocation.
# Opens a PR for human review. Never pushes to master directly.

set -euo pipefail

REPO_ROOT="/home/sanjayegupta/projects/elite-research-pipeline"
DATE=$(date +%F)
BRANCH="claude/weekly-scan-$DATE"
LOG_DIR="$REPO_ROOT/logs/weekly-scans"
LOG_FILE="$LOG_DIR/$DATE.log"
PROMPT_FILE="$REPO_ROOT/scripts/weekly-scan-prompt.md"
TARGET_FILE="knowledge-system/baseline/zone2-futures-intelligence/06-weak-signal-watch.md"

mkdir -p "$LOG_DIR"

# Send all output to both stdout and log file
exec > >(tee -a "$LOG_FILE") 2>&1

echo "==========================================="
echo "Weekly scan starting: $(date -u) UTC"
echo "==========================================="

cd "$REPO_ROOT"

# Ensure clean state on master
git checkout master
git pull origin master

# Abort if branch already exists (idempotency — don't overwrite prior scan)
if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
  echo "ERROR: Branch $BRANCH already exists locally. Investigate manually."
  exit 1
fi

if git ls-remote --exit-code --heads origin "$BRANCH" >/dev/null 2>&1; then
  echo "ERROR: Branch $BRANCH already exists on origin. Investigate manually."
  exit 1
fi

git checkout -b "$BRANCH"

# Run Claude Code in headless mode with Opus 4.7 + self-verification
# --print: non-interactive, output to stdout
# --permission-mode bypassPermissions: auto-approve all tools (needed for non-interactive web scans)
# --allowedTools: explicit whitelist — defense-in-depth alongside bypass mode
# --model opus: use Opus 4.7
# --effort xhigh: deep reasoning for signal scoring
# --max-budget-usd: safety ceiling to prevent runaway spend
# --output-format text: simple text output
claude \
  --print \
  --permission-mode bypassPermissions \
  --allowedTools "WebSearch" "WebFetch" "Read" "Write" "Edit" "Glob" "Grep" "Bash" \
  --model opus \
  --effort xhigh \
  --max-budget-usd 5.00 \
  --output-format text \
  < "$PROMPT_FILE"

# Commit and push only if there are changes to the target file
if git diff --quiet -- "$TARGET_FILE"; then
  echo "No changes to $TARGET_FILE — skipping commit and PR"
  git checkout master
  git branch -D "$BRANCH"
  echo "Scan complete (no signals found): $(date -u) UTC"
  exit 0
fi

# Only commit the target file — defensive against unrelated modifications
git add "$TARGET_FILE"
git commit -m "Weekly signal scan — $DATE

Automated Tier 2 source scan. Review before merging to master.

Generated by scripts/run-weekly-scan.sh"

git push origin "$BRANCH"

# Create PR
gh pr create \
  --title "Weekly signal scan — $DATE" \
  --body "Automated Tier 2 source scan from the weekly cron job.

**Sources scanned (16):**
- Synthesizers: Import AI, The Batch, One Useful Thing, Zvi, Stratechery
- Specialists: SemiAnalysis, Simon Willison, Latent Space, Interconnects, Gary Marcus, Pragmatic Engineer
- Workflow: Every/Chain of Thought, Hugging Face blog
- First-party: Anthropic News, OpenAI blog
- Indian perspective: Analytics India Magazine

**Review checklist:**
- [ ] Each new signal's 5-dimension profile is correctly scored
- [ ] Category mapping is accurate
- [ ] No hype or noise crept through
- [ ] Scan summary numbers match entries added

Run log: \`$LOG_FILE\`" \
  --base master \
  --head "$BRANCH"

echo "==========================================="
echo "Weekly scan complete: $(date -u) UTC"
echo "==========================================="
