#!/bin/bash
# Monthly low-cadence source scan — runs via systemd user timer
# (monthly-scan.timer, 1st of month 03:00 UTC = 8:30 AM IST, Persistent=true).
# Covers sources that publish too infrequently for the weekly rotation.
# Uses Accenture Claude subscription via headless `claude --print` invocation.
# Opens a PR for human review. Never pushes to master directly.

set -euo pipefail

# Single-instance lock, shared with the weekly scan (same repo, same working
# tree). Waits up to 2h instead of corrupting an in-progress checkout.
LOCK_FILE="/tmp/elite-research-scan.lock"
exec 9>"$LOCK_FILE"
if ! flock -w 7200 9; then
  echo "ERROR: could not acquire scan lock within 2h — another scan still running?" >&2
  exit 1
fi

REPO_ROOT="/home/sanjayegupta/projects/elite-research-pipeline"
DATE=$(date +%F)
BRANCH="claude/monthly-scan-$DATE"
LOG_DIR="$REPO_ROOT/logs/monthly-scans"
LOG_FILE="$LOG_DIR/$DATE.log"
PROMPT_FILE="$REPO_ROOT/scripts/monthly-scan-prompt.md"
TARGET_FILE="knowledge-system/baseline/zone2-futures-intelligence/06-weak-signal-watch.md"

mkdir -p "$LOG_DIR"

exec > >(tee -a "$LOG_FILE") 2>&1

echo "==========================================="
echo "Monthly scan starting: $(date -u) UTC"
echo "==========================================="

cd "$REPO_ROOT"

# On any failure after branch creation, restore master and delete the scan
# branch so the next run starts clean (both prior monthly runs died on the
# budget cap and left the repo on the scan branch).
SCAN_BRANCH_ACTIVE=0
cleanup() {
  local rc=$?
  if (( rc != 0 && SCAN_BRANCH_ACTIVE == 1 )); then
    echo "ERROR: scan failed (exit $rc) — restoring master, deleting $BRANCH" >&2
    git checkout --force master 2>/dev/null || true
    git branch -D "$BRANCH" 2>/dev/null || true
  fi
}
trap cleanup EXIT

# --force: discard partial tracked-file edits left by a previously failed run.
git checkout --force master
git pull origin master

if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
  echo "ERROR: Branch $BRANCH already exists locally. Investigate manually."
  exit 1
fi

if git ls-remote --exit-code --heads origin "$BRANCH" >/dev/null 2>&1; then
  echo "ERROR: Branch $BRANCH already exists on origin. Investigate manually."
  exit 1
fi

git checkout -b "$BRANCH"
SCAN_BRANCH_ACTIVE=1

# --model sonnet + $10 cap: opus at xhigh effort blew the old $3 cap on both
# prior runs (May 1, Jun 1 2026) before producing any output.
# timeout 3600: wall-clock ceiling — budget caps spend, not time.
timeout 3600 claude \
  --print \
  --permission-mode bypassPermissions \
  --allowedTools "WebSearch" "WebFetch" "Read" "Write" "Edit" "Glob" "Grep" "Bash" \
  --model sonnet \
  --effort xhigh \
  --max-budget-usd 10.00 \
  --output-format text \
  < "$PROMPT_FILE"

if git diff --quiet -- "$TARGET_FILE"; then
  echo "No changes to $TARGET_FILE — skipping commit and PR"
  git checkout master
  git branch -D "$BRANCH"
  echo "Monthly scan complete (no signals found): $(date -u) UTC"
  exit 0
fi

git add "$TARGET_FILE"
git commit -m "Monthly low-cadence scan — $DATE

Automated scan of monthly sources (researcher blogs, lab blogs, benchmarks).
Review before merging to master.

Generated by scripts/run-monthly-scan.sh"

git push origin "$BRANCH"

# Body via quoted heredoc + envsubst — no shell interpolation pass (see
# run-weekly-scan.sh for rationale).
BODY_FILE=$(mktemp)
export LOG_FILE
envsubst '${LOG_FILE}' > "$BODY_FILE" <<'PR_BODY_EOF'
Automated monthly scan of low-cadence high-signal sources.

**Sources scanned:**
- Researcher blogs: Karpathy, Pranav Mistry / Presight AI
- Lab blogs: Google DeepMind, Gemini / Google AI
- Research feeds: DAIR AI (Elvis), Underfitted (Santiago)
- Benchmarks: SWE-bench, ARC-AGI

**Review checklist:**
- [ ] Each new signal's 5-dimension profile is correctly scored
- [ ] Category mapping is accurate
- [ ] No duplication with signals already captured by weekly scan
- [ ] Scan summary numbers match entries added

Run log: `${LOG_FILE}`
PR_BODY_EOF

gh pr create \
  --title "Monthly low-cadence scan — $DATE" \
  --body-file "$BODY_FILE" \
  --base master \
  --head "$BRANCH"
rm -f "$BODY_FILE"

# Leave the working tree on master; the pushed branch stays for the open PR.
git checkout master

echo "==========================================="
echo "Monthly scan complete: $(date -u) UTC"
echo "==========================================="
