#!/bin/bash
# Monthly low-cadence source scan — runs via system cron on 1st of month 6 AM IST
# Covers sources that publish too infrequently for the weekly rotation.
# Uses Accenture Claude subscription via headless `claude --print` invocation.
# Opens a PR for human review. Never pushes to master directly.

set -euo pipefail

REPO_ROOT="/home/sanjayegupta/projects/elite-research-pipeline"
DATE=$(date +%F)
BRANCH="claude/monthly-scan-$DATE"
LOG_DIR="$REPO_ROOT/logs/monthly-scans"
LOG_FILE="$LOG_DIR/$DATE.log"
PROMPT_FILE="$REPO_ROOT/scripts/monthly-scan-prompt.md"
TARGET_FILE="knowledge-system/baseline/zone2-futures-intelligence/06-weak-signal-watch.md"

mkdir -p "$LOG_DIR"

exec > >(tee -a "$LOG_FILE") 2>&1

echo "==========================================="
echo "Monthly scan starting: $(date -u) UTC"
echo "==========================================="

cd "$REPO_ROOT"

git checkout master
git pull origin master

if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
  echo "ERROR: Branch $BRANCH already exists locally. Investigate manually."
  exit 1
fi

if git ls-remote --exit-code --heads origin "$BRANCH" >/dev/null 2>&1; then
  echo "ERROR: Branch $BRANCH already exists on origin. Investigate manually."
  exit 1
fi

git checkout -b "$BRANCH"

claude \
  --print \
  --permission-mode bypassPermissions \
  --allowedTools "WebSearch" "WebFetch" "Read" "Write" "Edit" "Glob" "Grep" "Bash" \
  --model opus \
  --effort xhigh \
  --max-budget-usd 3.00 \
  --output-format text \
  < "$PROMPT_FILE"

if git diff --quiet -- "$TARGET_FILE"; then
  echo "No changes to $TARGET_FILE — skipping commit and PR"
  git checkout master
  git branch -D "$BRANCH"
  echo "Monthly scan complete (no signals found): $(date -u) UTC"
  exit 0
fi

git add "$TARGET_FILE"
git commit -m "Monthly low-cadence scan — $DATE

Automated scan of monthly sources (researcher blogs, lab blogs, benchmarks).
Review before merging to master.

Generated by scripts/run-monthly-scan.sh"

git push origin "$BRANCH"

gh pr create \
  --title "Monthly low-cadence scan — $DATE" \
  --body "Automated monthly scan of low-cadence high-signal sources.

**Sources scanned:**
- Researcher blogs: Karpathy, Pranav Mistry / Presight AI
- Lab blogs: Google DeepMind, Gemini / Google AI
- Research feeds: DAIR AI (Elvis), Underfitted (Santiago)
- Benchmarks: SWE-bench, ARC-AGI

**Review checklist:**
- [ ] Each new signal's 5-dimension profile is correctly scored
- [ ] Category mapping is accurate
- [ ] No duplication with signals already captured by weekly scan
- [ ] Scan summary numbers match entries added

Run log: \`$LOG_FILE\`" \
  --base master \
  --head "$BRANCH"

echo "==========================================="
echo "Monthly scan complete: $(date -u) UTC"
echo "==========================================="
